// Run with: bun scripts/generate-ai-models.ts
// Reads model data from @mariozechner/pi-ai and generates a lightweight TS data file

import { MODELS } from '../node_modules/@mariozechner/pi-ai/dist/models.generated.js';
import { writeFileSync } from 'fs';

// Map from MarkBun provider ID to pi-ai provider ID
const PIAI_PROVIDER_MAP: Record<string, string> = {
  anthropic: 'anthropic',
  openai: 'openai',
  google: 'google',
  openrouter: 'openrouter',
  minimax: 'minimax',
  glm: 'zai',
};

// Supplementary model lists for providers not in pi-ai
// Updated 2026-04 based on official API docs
const SUPPLEMENTARY: Record<string, string[]> = {
  // Ollama — most popular models by pull count (2026-04)
  ollama: [
    'qwen3', 'qwen2.5', 'deepseek-r1', 'llama3.1', 'llama3.2', 'llama3.3',
    'gemma3', 'gemma2', 'mistral', 'phi4', 'codellama', 'qwq',
    'qwen3-coder', 'qwen2.5-coder', 'llava',
  ],
  // DeepSeek API — api.deepseek.com (both powered by V3.2)
  deepseek: ['deepseek-chat', 'deepseek-reasoner'],
  // Kimi / Moonshot AI — platform.moonshot.cn
  kimi: ['kimi-k2.5', 'kimi-k2', 'kimi-k2-thinking', 'moonshot-v1-128k', 'moonshot-v1-32k', 'moonshot-v1-8k'],
  // Qwen / Alibaba Dashscope — dashscope.aliyuncs.com
  qwen: [
    'qwen3-max', 'qwen3-coder-plus', 'qwen3-coder-flash', 'qwen-plus',
    'qwen-flash', 'qwen-turbo', 'qwq-plus', 'qwen-long', 'qwen-max',
  ],
  // Doubao / ByteDance Volcengine — ark.cn-beijing.volces.com
  doubao: [
    'doubao-seed-2-0-pro-260215', 'doubao-seed-2-0-lite-260215',
    'doubao-seed-1-8-251228', 'doubao-seed-1-6-251015',
    'doubao-1-5-pro-256k-250115', 'doubao-1-5-pro-32k-250115', 'doubao-1-5-lite-32k-250115',
  ],
};

const lines: string[] = [
  '// Auto-generated by scripts/generate-ai-models.ts',
  '// Do not edit manually — run: bun scripts/generate-ai-models.ts',
  '',
  'export const AI_MODELS: Record<string, string[]> = {',
];

for (const [mbId, piaiId] of Object.entries(PIAI_PROVIDER_MAP)) {
  const providerModels = MODELS[piaiId as keyof typeof MODELS];
  if (providerModels) {
    const ids = Object.keys(providerModels);
    lines.push(`  ${JSON.stringify(mbId)}: ${JSON.stringify(ids)},`);
  }
}

for (const [id, models] of Object.entries(SUPPLEMENTARY)) {
  lines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(models)},`);
}

lines.push('  "custom": [],');
lines.push('};');
lines.push('');

writeFileSync('src/mainview/lib/ai-models-data.ts', lines.join('\n'));
console.log('Generated src/mainview/lib/ai-models-data.ts');
